### ISSUE TITLE
Bug if aws-sdk is install into functions folders

### ISSUE THREAD

**Issue by kevinsimper** [arc-repos/arc-workflows#6] opened 2017-08-05 22:08 UTC
If you install `aws-sdk` into the functions folders, it will fail before you own code even fails.

It is not because I forgot to set the region.

```
var arc = require('@architect/functions')

var AWS = require('aws-sdk')

function route(req, res) {
  console.log('kevin')
  AWS.config.update({region: 'us-east-1'});
  console.log(AWS.config)
  var endpoint  = new AWS.Endpoint('http://localhost:5000')
  var dynamo = new AWS.DynamoDB({endpoint})
  dynamo.listTables({}, function _list(err, result) {
    console.log(err, result)
  })
  console.log(JSON.stringify(req, null, 2))
  res({
    json: {msg:`hello world sam`}
  })
}

exports.handler = arc.json.get(route)
```

```
Started db @ http://localhost:5000
@json get /api.............................. get-api
@html get /................................. get-index
Started http @ http://localhost:3333
/Users/kevinsimper/Projects/test/architect/src/json/get-api/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

ConfigError: Missing region in config
    at Request.VALIDATE_REGION (/test/architect/src/json/get-api/node_modules/aws-sdk/lib/event_listeners.js:91:45)
```

"kevin" is never outputted

**Comment by kevinsimper** [comment] 2017-08-05 23:24
```
$ NODE_ENV=testing ./node_modules/.bin/arc-sandbox
```

it only happens when `NODE_ENV=testing` is set, does not happen if you run it without

**Comment by brianleroux** [comment] 2017-08-06 20:29
yeah this is a docs issue; I _think_ we want to be explicit about setting REGION as env vars---wydt?

**Comment by kevinsimper** [comment] 2017-08-06 20:41
Yeah, I think you want to be explicit, but I don't understand for developing with the sandbox?

**Comment by brianleroux** [comment] 2017-08-07 00:57
The Dynamo client in the AWS SDK needs region specified (because dynamo does) and you def do not want to hardcode that --- an env var seems suitable '12 factor app' for that.  That said, this is def a bug w the docs!

**Comment by kborchers** [comment] 2017-08-07 22:24
Hmm, I think there is still a bug here beyond the docs. Trying to track it down but what I am seeing is that no matter what I set as `AWS_REGION`, the `arc-sandbox` DB is always running at `us-east-1`. This doesn't even align with the hard-coded region set in `_get-db-client.js` and `_get-doc-client.js` which is set to `us-west-1`. The default in dynalite is `us-east-1` so apparently something is breaking down and causing dynalite to fall to its default when standing up the DB.

**Comment by brianleroux** [comment] 2017-08-08 00:46
eh @kborchers ! 

created a repo to help create some steps to reproduce 
https://github.com/brianleroux/arc-sandbox-debug/

in particular check out `./tests` for how I use dynamo w the sandbox (should be same for app functions logic)
https://github.com/brianleroux/arc-sandbox-debug/blob/master/test/db-test.js

**Comment by brianleroux** [comment] 2017-08-12 04:16
Closing this issue (and do have more Dynamo docs en route)

**Closed by brianleroux** 2017-08-12 04:16 UTC
Labels: bug
