### ISSUE TITLE
Issue providing status codes for JSON responses

### ISSUE THREAD

**Issue by jondavidjohn** [arc-repos/arc-workflows#30] opened 2017-11-17 05:49 UTC
When trying to supply a `403` status to a json response call

```js
res({
  status: 403,
  json: { error: 'Not Authorized' }
})
```

My local dev environment halts with the following output

```
undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at _local (.../node_modules/@architect/workflows/src/sandbox/http/index.js:83:48)
    at Object._err (.../node_modules/@architect/functions/src/http/_err.js:35:3)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:329:26)
```

**Comment by brianleroux** [comment] 2017-11-17 17:39
oh noessss, I'll have a look !

**Comment by jondavidjohn** [comment] 2017-12-12 20:45
This also happens when you use the middleware pattern and call `next` with an instance of an error.

```
function authorize (req, res, next) {
  next(new Error('Error!'))
}

...

exports.handler = arc.json.get(authorize, route)
```

Would expect a 500 status code in this instance.

**Comment by brianleroux** [comment] 2018-02-16 01:05
Ok! Apologize for the wait. For the first issue I was unable to reproduce. (Created a test repo here: https://github.com/arc-repos/arc-example-json-status-codes)

The second thing is interesting and I hadn't considered it. Right now `next` takes no arguments it just kicks up the next function in the middleware queue. I deliberately chose to not allow state passing between middlewares. Controversial perhaps but its for our own good. State between functions means order dependent stuff starts to happen and I've found that to be mega brittle. Open to discussing it further tho. Nothing needs to be set in stone. Esp w JS!

If you want middleware to error out when working locally it will crash the process with a legit stack trace. This too is deliberate. Way easier to debug. On `staging` and `production` you'll get nicely formatted errors (usually) with a stack trace. You just pass the error to `res` like this:

```
function middleware(req, res, next) {
  res(Error('boom')) 
}
```

<img width="900" alt="screen shot 2018-02-15 at 4 59 26 pm" src="https://user-images.githubusercontent.com/990/36288935-1d64e6a6-1272-11e8-9466-ff7b30467003.png">

Closing for now but would def appreciate your feedback and thoughts on the above!

**Closed by brianleroux** 2018-02-16 01:05 UTC
Labels: bug

**Comment by jondavidjohn** [comment] 2018-02-16 16:31
> Apologize for the wait. For the first issue I was unable to reproduce.

NP, Thanks for checking, It's been a minute since I've worked on this project.  I'll upgrade everything and test again.

> Right now next takes no arguments it just kicks up the next function in the middleware queue.

Got it.  Probably an expectation I got from using express middleware, I see the error usage with `res` clearly in the docs, that should work thanks!

> The second thing is interesting and I hadn't considered it. Right now next takes no arguments it just kicks up the next function in the middleware queue. I deliberately chose to not allow state passing between middlewares. Controversial perhaps but its for our own good. State between functions means order dependent stuff starts to happen and I've found that to be mega brittle. Open to discussing it further tho. Nothing needs to be set in stone. Esp w JS!

Sure this makes sense, though it may conflict with the suggestion that we should be mutating `req` to pass state (like adding a `req.user` for example).  I have no problem using `req(new Error())`, but maybe making `next(new Error())` equivalent might have some express compatibility benefits?  Honestly haven't thought much about it.
